name: fursan_travel_app
description: "An awesome Tourism App for travels and booking "
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"


# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl_utils: ^2.8.7
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  get_it: ^8.0.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  data_connection_checker_tv: ^0.3.5-nullsafety
  internet_connection_checker: ^1.0.0+1
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  dartz: ^0.10.1
  in_app_update: ^4.2.3
  iconsax: ^0.0.8
  flutter_bloc: ^8.1.6
  animated_bottom_navigation_bar: ^1.3.3
  page_transition: ^2.1.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  flutter_html: ^3.0.0-beta.2

#-------------------- PACKAGES End --------------------#
dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter
flutter_icons:
  android: "flutter_luancher"
  ios: true
  image_path: "assets/images/pngs/img.png"


  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/lotties/
    - assets/animations/
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/images/jpegs/
    - assets/images/pngs/social_images/
    - assets/images/GIF/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ar/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Cairo-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/en/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/en/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/en/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/en/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/en/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/en/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/en/Poppins-Bold.ttf
          weight: 800
    - family: Alexandria
      fonts:
        - asset: assets/fonts/ar/Alexandria-Light.ttf
          weight: 300
        - asset: assets/fonts/ar/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/ar/Alexandria-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Alexandria-Bold.ttf
          weight: 800

flutter_intl:
  enabled: true